### ISSUE TITLE
Rotana.net ini file

### ISSUE THREAD

**Issue by bebawy6** [Fazzani/grab#11]
I was hoping that you can create an INI file for webgraber for rotana.net/epg/  website as you know Rotana Channels is not available any more in Elcenima.com
and now they have their own in  https://rotana.net/epg/

**Comment by Fazzani** [comment]
I'll take a look as soon as possible

**Comment by themak1985** [comment]
Update: https://rotana.net/%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D8%A8%D8%B1%D8%A7%D9%85%D8%AC/

**Comment by LaneSh4d0w** [comment]
> 
> 
> Update: https://rotana.net/%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D8%A8%D8%B1%D8%A7%D9%85%D8%AC/

Something interesting to note : the channels are sorted... by a few CSV files that Rotana has uploaded in their servers.

The server only picks the date and the scripts are charged of doing the rest.

**Comment by bebawy6** [comment]
[rotana.net.ini.txt](https://github.com/Fazzani/grab/files/6053637/rotana.net.ini.txt)
[rotana.net.channels.xml.txt](https://github.com/Fazzani/grab/files/6053638/rotana.net.channels.xml.txt)

Hello there,

attached is the ini file and channel list created by mat8861. it is not working correctly but I share with you.... Note I added .txt at the end of the file for github to allow attaches them. please remove .txt from the end of the file.
bet regards
