### ISSUE TITLE
Source Replacment

### ISSUE THREAD

**Issue by MuazT** [Fazzani/grab#9]
Hi,

is it possible to replace the Arabic channels source from osn to elcinema.com because almost all the Arabic channels have no programs found.

http://www.webgrabplus.com/sites/default/files/download/ini/info/zip/Egypt_elcinema.en.com.zip

Best Regards.

**Comment by Fazzani** [comment]
elcinema can be founded here. I grab both (osn and elcinema)
https://github.com/Fazzani/grab/blob/master/ar_el_cinema.xmltv
